### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by benjmd** [mutschler/plexivity#1]
Just wondering if there are plans to create a docker image for this one?

**Comment by mutschler** [comment]
i've made a docker image: docker hub: https://hub.docker.com/r/mutschler/plexivity/
if you want to build it yourself, the code is up here: https://github.com/mutschler/docker-plexivity

**Comment by benjmd** [comment]
Thanks mutschler, not sure if there's something I'm doing wrong but this container is indestructible/can't be removed (moving NAS's).

**Comment by mutschler** [comment]
What NAS See you using? I'm not using docker for this myself but I've tested the container when I created it and everything worked fine for me.

**Comment by benjmd** [comment]
Synology DS2411+, I noticed a whole host of other issues with docker (duplicate containers etc) so I was uninstalling all to try and work out where it went bad.

**Comment by mutschler** [comment]
Maybe that's a problem with the sicker implementation on your NAS itself... If you have duplicate containers etc I guess there is something wrong :/

**Comment by benjmd** [comment]
Thats what I thought, hence the removing of all other docker containers.
I'm going to stick with the synology .spks for the time being, they appear to be heaps more stable and have less issues. Thanks for the help :)

**Comment by mutschler** [comment]
You`re welcome. If you change your mind and move back to the docker containers let me know ;)

**Comment by benjmd** [comment]
Once I am smarter, for sure :)
